const actions = {
	ADD_TO_CART: "ADD_TO_CART",
	EMPTY_CART: "EMPTY_CART",
	REMOVE_FROM_CART: "REMOVE_FROM_CART",
	COUNT_CART: "COUNT_CART",
	TOTAL_CART: "TOTAL_CART",
	INCREMENT: "INCREMENT",
	DECREMENT: "DECREMENT",
};
export default actions;
